name: Package and Release

on:
  push:
    branches:
      - master
    tags:
      - '*'
      - '!**-classic'
    paths-ignore:
      - '.github/**'

jobs:

  release:

    runs-on: ubuntu-latest
    environment: Packager # name of the custom environment containing the secrets

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow

    steps:

      - name: Clone Project
        uses: actions/checkout@v1

      - name: Package and Release
        uses: BigWigsMods/packager@master
